version: "2"
volumes:
  personal_id_rsa:
  jenkins_home:
  gitlab_config:
  gitlab_data:
  gitlab_log:
services:
  canalsevere:
    build: dockers/cloud9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - personal_id_rsa:/opt/personal/id_rsa
      - personal_gpg_secret_key:/opt/personal/gpg/secret_key
      - personal_gpg_owner_trust:/opt/personal/gpg/owner_trust
      - jenkins_home:/opt/jenkins/home
      - gitlab_config:/opt/gitlab/config
      - gitlab_data:/opt/gitlab/data
      - gitlab_log:/opt/gitlab/log
    ports:
      - 8080
    links:
      - gitlab
      - jenkins
    environment:
      - EMAIL=emory.merryman@gmail.com
      - NAME=Emory Merryman
      - CANONICAL_URL=git@github.com:desertedscorpion/canalsevere.git
      - ORIGIN_URL=git@github.com:desertedscorpion/canalsevere.git
    privileged: true
  gitlab:
    image: gitlab/gitlab-ce:8.9.6-ce.0
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_log:/var/log/gitlab
      - gitlab_config:/etc/gitlab
    ports:
      - 443
      - 80
      - 22
  jenkins:
    build: dockers/jenkins
    ports:
      - 8080
      - 50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    privileged: true