version: "2"
volumes:
  personal_private:
  personal_id_rsa:
  personal_gpg_secret_key:
  personal_gpg_owner_trust:
  jenkins_home:
  gitlab_config:
  gitlab_data:
  gitlab_log:
services:
  runner:
    image: gitlab/gitlab-runer:v1.4.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
  canalsevere:
    build: dockers/cloud9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - personal_private:/opt/personal/private
      - jenkins_home:/opt/jenkins/home
      - gitlab_config:/opt/gitlab/config
      - gitlab_data:/opt/gitlab/data
      - gitlab_log:/opt/gitlab/log
    ports:
      - 8080
    links:
      - gitlab
      - jenkins
    environment:
      - EMAIL=emory.merryman@gmail.com
      - NAME=Emory Merryman
      - CANONICAL_URL=git@github.com:desertedscorpion/canalsevere.git
      - ORIGIN_URL=git@github.com:desertedscorpion/canalsevere.git
    privileged: true
  goldencoffin:
    build: dockers/cloud9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - personal_private:/opt/personal/private
      - jenkins_home:/opt/jenkins/home
      - gitlab_config:/opt/gitlab/config
      - gitlab_data:/opt/gitlab/data
      - gitlab_log:/opt/gitlab/log
    ports:
      - 8080
    links:
      - gitlab
      - jenkins
    environment:
      - EMAIL=emory.merryman@gmail.com
      - NAME=Emory Merryman
      - CANONICAL_URL=git@gitlab:bravemicrophone/goldencoffin.git
      - ORIGIN_URL=git@gitlab:bravemicrophone/goldencoffin.git
    privileged: true
  gitlab:
    build: dockers/gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_data:/var/opt/gitlab
      - gitlab_log:/var/log/gitlab
      - gitlab_config:/etc/gitlab
    ports:
      - 443
      - 80
      - 22
    privileged: true
  jenkins:
    build: dockers/jenkins
    ports:
      - 8080
      - 50000
    links:
      - gitlab
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    privileged: true