version: "2"
services:
  canalsevere:
    build: dockers/cloud9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa:ro
    ports:
      - 8080
    links:
      - gitlab
      - jenkins
    environment:
      - CANONICAL_URL="git@github.com:desertedscorpion/canalsevere.git"
      - ORIGIN_URL="git@github.com:desertedscorpion/canalsevere.git"
    privileged: true
  gitlab:
    image: gitlab/gitlab-ce:8.9.6-ce.0
    volumes:
      - ./volumes/gitlab/data:/var/opt/gitlab
      - ./volumes/gitlab/logs:/var/log/gitlab
      - ./volumes/gitlab/gitlab:/etc/gitlab
    ports:
      - 443
      - 80
      - 22
  jenkins:
    image: jenkins:2.7.1-alpine
    ports:
      - 8080
      - 50000
    volumes:
      - ./volumes/jenkins:/var/jenkins_home