version: "2"
volumes:
  personal_id_rsa:
  jenkins_home:
  gitlab_config:
  gitlab_data:
  gitlab_log:
services:
  canalsevere:
    build: dockers/cloud9
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - personal_id_rsa:/opt/personal/id_rsa
      - jenkins_home:/opt/jenkins/home:ro
      - gitlab_config:/opt/gitlab/config:ro
      - gitlab_data:/opt/gitlab/data:ro
      - gitlab_log:/opt/gitlab/log:ro
    ports:
      - 8080
    links:
      - gitlab
      - jenkins
    environment:
      - EMAIL=emory.merryman@gmail.com
      - NAME=Emory Merryman
      - CANONICAL_URL=git@github.com:desertedscorpion/canalsevere.git
      - ORIGIN_URL=git@github.com:desertedscorpion/canalsevere.git
    privileged: true
  gitlab:
    image: gitlab/gitlab-ce:8.9.6-ce.0
    volumes:
      - gitlab_data:/var/opt/gitlab
      - gitlab_log:/var/log/gitlab
      - gitlab_config:/etc/gitlab
    ports:
      - 443
      - 80
      - 22
  jenkins:
    image: jenkins:2.7.1-alpine
    ports:
      - 8080
      - 50000
    volumes:
      - jenkins_home:/var/jenkins_home