version: "2"
services:
  cloud9:
    build: dockers/cloud9
    volumes:
      - ./workspace:/var/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080
    links:
      - gitlab
      - jenkins
    privileged: true
  git:
    build: dockers/git
    volumes:
      - ./workspace:/var/workspace
    environment:
      CANONICAL: ${CANONICAL}
      ORIGIN: ${ORIGIN}
  gitlab:
    image: gitlab/gitlab-ce:8.9.6-ce.0
    volumes:
      - ./volumes/gitlab/data:/srv/gitlab/data
      - ./volumes/gitlab/logs:/srv/gitlab/logs
      - ./volumes/gitlab/gitlab:/etc/gitlab
    ports:
      - 443
      - 80
      - 22
    links:
      - jenkins
  jenkins:
    image: jenkins:2.7.1-alpine
    ports:
      - 8080
      - 50000
    volumes:
      - ./volumes/jenkins:/var/jenkins_home
    links:
      - gitlab
      