version: "2"
services:
  cloud9:
    build: dockers/cloud9
    volumes:
      - ./workspace:/var/workspace
    ports:
      - 8080
  git:
    build: dockers/git
    volumes:
      - ./workspace:/var/workspace
    environment:
      CANONICAL: ${CANONICAL}
      ORIGIN: ${ORIGIN}